## Creating different types of arrays

In [2]:
#  from list and tuple we can create numpy array 
import numpy as np


a = np.array([1, 2, 3])
b = np.array((4, 5, 6))

print("using list we created numpy array :- ",a)
print("using tuple we created numpy array :- ",b)

using list we created numpy array :-  [1 2 3]
using tuple we created numpy array :-  [4 5 6]


In [6]:
# Common Array Creation Functions

c = np.zeros((2, 3))         # 2x3 matrix of 0s  ((rows ,columns))
d = np.ones((2, 2))          # 2x2 matrix of 1s

print(" using np.zeros we created 2X3 matrix of 1 elements :- \n",c,"\n")
print("using np.ones we created 2X2 matrix of 0 elements:- \n",d,"\n")

t = np.arange(0,10)
print(t,"\n")

e = np.arange(0, 10, 2)      # [0, 2, 4, 6, 8] arange is for loop it has start,end,step 
print("arange is for loop ,it starts from 0 ,ends 10 step is 2 we are finding even numbers :-\n",e,"\n") 

f = np.arange(0, 10, 1)
print("arange is for loop ,it starts from 0 ,ends 10 step is 1 we are finding odd numbers :-\n",f,"\n")

 using np.zeros we created 2X3 matrix of 1 elements :- 
 [[0. 0. 0.]
 [0. 0. 0.]] 

using np.ones we created 2X2 matrix of 0 elements:- 
 [[1. 1.]
 [1. 1.]] 

[0 1 2 3 4 5 6 7 8 9] 

arange is for loop ,it starts from 0 ,ends 10 step is 2 we are finding even numbers :-
 [0 2 4 6 8] 

arange is for loop ,it starts from 0 ,ends 10 step is 1 we are finding odd numbers :-
 [0 1 2 3 4 5 6 7 8 9] 



## Array Attributes

In [7]:
# dtype is used to find out the data type of an elements in an array

arr = np.array([1, 2, 3], dtype=float) # dtype data type of an element in an array
print(arr.dtype)  # float64 


float64


In [9]:
a1 = arr.ndim       # Number of dimensions
a2 = arr.shape      # Shape (rows, cols)
a3 = arr.size       # Total number of elements
a4 = arr.dtype      # Data type
a5 = arr.itemsize   # Size in bytes of each element

print("arr.ndim is used to display Number of dimensions :- ",a1,"\n")
print("arr.shape is used to display Shape (rows, cols) :- ",a2,"\n")
print("arr.size is used to display Total number of elements :- ",a3,"\n")
print("arr.dtype is used to display data type of elements :- ",a4,"\n")
print("arr.itemsize is used to display Size in bytes of each element :- ",a5,"\n")

arr.ndim is used to display Number of dimensions :-  1 

arr.shape is used to display Shape (rows, cols) :-  (3,) 

arr.size is used to display Total number of elements :-  3 

arr.dtype is used to display data type of elements :-  float64 

arr.itemsize is used to display Size in bytes of each element :-  8 



### Indexing and Slicing

In [10]:
 # Basic Indexing

arr = np.array([10, 20, 30, 40])
print("accessing 0th index of an array:- ",arr[0])         # 10
print("accessing -1th index of an array:- ",arr[-1])        # 40


accessing 0th index of an array:-  10
accessing -1th index of an array:-  40


In [13]:
# 2D Indexing

mat = np.array([[1, 2], [3, 4]])

print("this is 2-D array :-\n",mat)

print("="*30)

print("[0][1] 0th-> [1,2] for this 1th->[2]")
print("0 represent the 0th row for this we are accessing 1th column of it :- ",mat[0][1])     # 2


this is 2-D array :-
 [[1 2]
 [3 4]]
[0][1] 0th-> [1,2] for this 1th->[2]
0 represent the 0th row for this we are accessing 1th column of it :-  2


In [14]:
# Slicing

print(arr)
print(arr[1:4])       # [20, 30, 40]
print(arr[:3])        # [10, 20, 30]
print(arr[::-1])      # Reverse array


[10 20 30 40]
[20 30 40]
[10 20 30]
[40 30 20 10]


In [16]:
# Boolean Indexing

# we can check the values which are greater then 25 in an array 
# array[array with condition]

print(arr[arr > 25])   # Filter elements greater than 25

print(arr[arr > 55])

[30 40]
[]


In [17]:
# Fancy Indexing

# arr[[index,]] we can directily access the values using index 

print(arr[[0, 2]])     # Select 0th and 2nd elements


[10 30]


## Array Operations 

In [18]:
# Arithmetic Operations

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)           # [5, 7, 9] adding two arrays
print(a * b)           # [4, 10, 18] mutipleing two array 


[5 7 9]
[ 4 10 18]


In [25]:
# Scalar Operations
# using sinle value we can  performing operations 

# Scalar means:
# A single value.

# we can mutiple by 2 for each element in an array

print(a * 2)           # [2, 4, 6]
print(a + 5)           # here 2 and 5 are the scaler using scaler we are performing operations 


#  vectorization
# Vectorization means performing operations on the complete array without using loops. 
# vectorization is performing an operation on all elements inside an array without writing sperate code for it(explicite program)

arr = np.array([10, 20, 30])
print(arr + 5)

[2 4 6]
[6 7 8]
[15 25 35]


In [20]:
# Broadcasting

# performaing an operation two different arrays with different shapes

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
num = np.array([10, 20, 30])

print(arr)
print("+"*40)
print(num)
print("+"*40)
print(arr+num)

[[1 2 3]
 [4 5 6]]
++++++++++++++++++++++++++++++++++++++++
[10 20 30]
++++++++++++++++++++++++++++++++++++++++
[[11 22 33]
 [14 25 36]]


In [21]:
# Comparison

# we can give the condition also to check the value is greater then 2 or not 

print(a > 2)           # [False, False, True]


[False False  True]


## Array Manipulation

Reshape & Resize

In [31]:
# Reshaping
# it is used to reshape the array not the resize the array just reshape the array 

arr = np.arange(6)
print("Original array :- ",arr)

arr1 = arr.reshape((2, 3))
print("reshapeing to 2 rows 3 columns :- \n",arr1)

arr2 = arr.reshape((3, 3))
print("reshapeing to 2 rows 3 columns :- \n",arr2)



# here why i m getting an error because of number of elements that are not matched to the array size 
# array size is it allows only 6 elements but i m trying to do 3X3 which is 9 elements so for this i m getting an error 

Original array :-  [0 1 2 3 4 5]
reshapeing to 2 rows 3 columns :- 
 [[0 1 2]
 [3 4 5]]


ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
# resize used to change the array 
# here we can see that still values are missing so it will not generated error insted of replace missing values with 0 
a1 = np.arange(6)
print(a1)
a1.resize((3, 3))
print("reshapeing to 3 rows 3 columns :- \n",a1)

print("-"*30)
arr = np.array([1, 2, 3, 4, 5, 6,8,9,10,11,12])
arr.resize((3, 3))
print(arr)

[0 1 2 3 4 5]
reshapeing to 3 rows 3 columns :- 
 [[0 1 2]
 [3 4 5]
 [0 0 0]]
------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


## Flatten & ravel

In [36]:
# flatten and ravel 


# flatten()
# Converts multi-dimensional array into 1D array.
# Creates a copy of the data.
# If you change the original array → it does not affect the flattened array.

# ravel()
# Also converts multi-dimensional array into 1D array.
# Creates a view of the data.
# If you change the original array → it will affect the raveled array (since both share the same memory).

arr = np.array([[1, 2], [3, 4]])

flat1 = arr.flatten()  # Copy ,flatten used to convert mutiple-demenstional array to one-demenetional array
ravel1 = arr.ravel()    # View , display view of array 

arr[0][1] = 20 # changed the value

print("Original:\n", arr)
print("Flatten:\n", flat1)
print("Ravel:\n", ravel1) # ravel got changed when i changed original array it will effecting to ravel array


Original:
 [[ 1 20]
 [ 3  4]]
Flatten:
 [1 2 3 4]
Ravel:
 [ 1 20  3  4]


### Copy() & View()

In [44]:
# copy()
# it will copy the content 

arr1 = np.array([[1, 2], [3, 4]])
print("original array\n",arr1)

print("+"*50)

arr2 = arr1.copy()
print("copied array arr2\n",arr2)
print("+"*50)

print("arr1 id", id(arr1))
print("arr2 id", id(arr2))
print("+"*50)

arr1[1][0] = 30 # changed arr1 
print("changes in arr1 \n", arr1)
print("not changes in arr2 \n", arr2)

original array
 [[1 2]
 [3 4]]
++++++++++++++++++++++++++++++++++++++++++++++++++
copied array arr2
 [[1 2]
 [3 4]]
++++++++++++++++++++++++++++++++++++++++++++++++++
arr1 id 1773660725360
arr2 id 1773660896400
++++++++++++++++++++++++++++++++++++++++++++++++++
changes in arr1 
 [[ 1  2]
 [30  4]]
not changes in arr2 
 [[1 2]
 [3 4]]


In [47]:
# view()
# it will view the content 

arr1 = np.array([[1, 2], [3, 4]])
print("original array\n",arr1)

print("+"*50)

arr2 = arr1.view()
print("copied array arr2\n",arr2)
print("+"*50)

print("arr1 id", id(arr1))
print("arr2 id", id(arr2))
print("+"*50)

arr1[1][0] = 300 # changed arr1 
print("changes in arr1 \n", arr1)
print("changes in arr2 \n", arr2)

original array
 [[1 2]
 [3 4]]
++++++++++++++++++++++++++++++++++++++++++++++++++
copied array arr2
 [[1 2]
 [3 4]]
++++++++++++++++++++++++++++++++++++++++++++++++++
arr1 id 1773660727280
arr2 id 1773660896400
++++++++++++++++++++++++++++++++++++++++++++++++++
changes in arr1 
 [[  1   2]
 [300   4]]
changes in arr2 
 [[  1   2]
 [300   4]]


## shallow & deep copy 

In [ ]:
import copy

# in shallow copy if inner list is also shared the value will get change 
# if outer list is only shared if we try to make changes to original array also it will not effect 

# deepcopy is when we changed the original array will not effect even it is inner or outer list is shared it will not effect for deepcopy


original = [[1, 2], [3, 4]]

normal = original
shallow = copy.copy(original)
deep = copy.deepcopy(original)

normal[0][0] = 100

print("Original :", original)  # Changed
print("Normal   :", normal)    # Changed
print("Shallow  :", shallow)   # Changed because inner list is shared
print("Deep     :", deep)      # Not changed

print("-"*50)
normal[1] = [33,44] 

print("Original :", original)  # Changed
print("Normal   :", normal)    # Changed
print("Shallow  :", shallow)   # not Changed because outer list is shared
print("Deep     :", deep)      # Not changed

Original : [[100, 2], [3, 4]]
Normal   : [[100, 2], [3, 4]]
Shallow  : [[100, 2], [3, 4]]
Deep     : [[1, 2], [3, 4]]
--------------------------------------------------
Original : [[100, 2], [33, 44]]
Normal   : [[100, 2], [33, 44]]
Shallow  : [[100, 2], [3, 4]]
Deep     : [[1, 2], [3, 4]]


In [49]:
# rows coverted to columns and columns converted to rows 

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original:\n", arr)
print("Transpose:\n", arr.T)


Original:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


### concatenate() and vstack() and hstack()

In [50]:
# concaionaion used to join two variables   

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print("original :-a\n",a)
print("-------------------------------")
print("original :-b\n",b)
# Concatenate along axis 0 (vertically)
print("-------------------------------")
print("after the concatenate axis = 0 means vetrically")
print(np.concatenate((a, b), axis=0))
print("-------------------------------")
# Concatenate along axis 1 (horizontally)
# Only works if shapes match appropriately
a = np.array([[1,1], [2,2]])
b = np.array([[3,3], [4,4]])
print("original :-a\n",a)
print("-------------------------------")
print("original :-b\n",b)
print("-------------------------------")
print("after the concatenate axis = 1 means horizontally")
print(np.concatenate((a, b), axis=1))


original :-a
 [[1 2]
 [3 4]]
-------------------------------
original :-b
 [[5 6]]
-------------------------------
after the concatenate axis = 0 means vetrically
[[1 2]
 [3 4]
 [5 6]]
-------------------------------
original :-a
 [[1 1]
 [2 2]]
-------------------------------
original :-b
 [[3 3]
 [4 4]]
-------------------------------
after the concatenate axis = 1 means horizontally
[[1 1 3 3]
 [2 2 4 4]]


In [51]:
# vstack is used to stttore the data in vertical
# hstack is used to stttore the data in horizontal

a = np.array([1, 2])
b = np.array([3, 4])

print("Vertical Stack:\n", np.vstack((a, b)))
print("Horizontal Stack:\n", np.hstack((a, b)))

Vertical Stack:
 [[1 2]
 [3 4]]
Horizontal Stack:
 [1 2 3 4]


In [52]:
# split is used to split the data 
# np.split(variable , how many parts)

arr = np.array([10, 20, 30, 40, 50, 60])

# Split into 3 equal parts
split_arr = np.split(arr, 3)
print("Split arrays:", split_arr)


Split arrays: [array([10, 20]), array([30, 40]), array([50, 60])]


## statistics 

In [53]:
arr = np.array([10, 20, 30, 40, 50, 60])

a = np.sum(arr) # sum of all elements in array
b = np.mean(arr) # find the mean 
c = np.std(arr) # stander deviation
d = np.var(arr) # verance
e = np.min(arr) # min
f = np.max(arr) # max 
g = np.median(arr) # median

print("sum of all elements in array :- ",a)
print("find mean of array:- ",b)
print(c)
print(d)
print(e)
print(f)
print(g)

sum of all elements in array :-  210
find mean of array:-  35.0
17.07825127659933
291.6666666666667
10
60
35.0


In [54]:
arr = np.array([[1,2],[3,4]])

print("original :-\n",arr)

t = np.sum(arr, axis=0)   # Column-wise sum
t1 = np.sum(arr, axis=1)   # Row-wise sum

print("axis=0 column wise sum :- ",t)
print("axis=1 row wise sum :- ",t1)

original :-
 [[1 2]
 [3 4]]
axis=0 column wise sum :-  [4 6]
axis=1 row wise sum :-  [3 7]


In [55]:
d = np.random.rand(3, 2)        # Uniform distribution 0 to 1(np.randome.rand(rows,columns))
d1 = np.random.randn(3, 2)       # Normal distribution -ve to +ve (randome.randn(rows,columns))
d2 = np.random.randint(0, 10, 5) # Random ints size is 5 and 0 to 10 randome (randome.randint(starts,ends,size))

print("create array of 3X2 randome values from 0 to 1 :- \n",d)
print("create array of 3X2 randome values from -ve to +ve :- \n",d1)
print("create array and size of 5 and randome values from 0 to 10 :- \n",d2)



create array of 3X2 randome values from 0 to 1 :- 
 [[0.92036999 0.36524852]
 [0.41928343 0.66300794]
 [0.92418841 0.6796183 ]]
create array of 3X2 randome values from -ve to +ve :- 
 [[ 0.10513557  1.66849823]
 [ 0.19879463  0.51363952]
 [-1.15921127  0.35514867]]
create array and size of 5 and randome values from 0 to 10 :- 
 [2 9 0 4 5]


In [56]:
# where is used to give the conditional selection

arr = np.array([10, 20, 30, 40])

result = np.where(arr >= 30, "High", "Low")

print(result)

['Low' 'Low' 'High' 'High']
