### What is NumPy?

NumPy is a Python library for numerical calculations and arrays.


In [ ]:
# importing numpy 

import numpy as np

In [ ]:
# creating array

sales = np.array([100, 200, 300, 400, 500])

In [3]:
sales

array([100, 200, 300, 400, 500])

In [5]:
# shape
# sales array is 1-D and it has 1 row and 5 columns
sales.shape

(5,)

In [7]:
# 2D array

marks = np.array([
    [80, 75, 90],
    [65, 70, 85],
    [90, 95, 88]
])

print(marks.shape) # 3rows , 3 columns 

(3, 3)


In [9]:
# Mathematical operations

sales + 10


array([110, 210, 310, 410, 510])

In [10]:
sales * 2


array([ 200,  400,  600,  800, 1000])

In [11]:
sales / 2

array([ 50., 100., 150., 200., 250.])

In [12]:
sales ** 2


array([ 10000,  40000,  90000, 160000, 250000])

In [14]:
# creating zeros and ones array

zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
ones = np.ones((4,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
sales = np.array([100, 200, 300, 400, 500])
print(sales)



marks = np.array([
    [80, 75, 90],
    [65, 70, 85],
    [90, 95, 88]
])

print(marks)


# Find:

# Total
# Average
# Maximum
# Minimum
# Sales + 10
# Sales × 2

# Then use the marks array above and find:

# Shape
# Average
# Maximum
# Minimum
# First student's marks
# Second subject's marks

[100 200 300 400 500]
[[80 75 90]
 [65 70 85]
 [90 95 88]]


In [27]:
print("total - ",np.sum(sales))
print("avgrage - ",np.average(sales))
print("Maximum - ",np.max(sales))
print("Minimum - ",np.min(sales))
print("sales + 10 - ",sales + 10)
print("sales *2 - ",sales *2)

total -  1500
avgrage -  300.0
Maximum -  500
Minimum -  100
sales + 10 -  [110 210 310 410 510]
sales *2 -  [ 200  400  600  800 1000]


In [29]:
print(marks.shape)
print(np.average(marks))
print(np.max(marks))
print(np.min(marks))
print(marks[0])
print(marks[1])

(3, 3)
82.0
95
65
[80 75 90]
[65 70 85]
